server:
  port: 8086

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/git-piyush/microservice-config
          cloud-on-start: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8084/eureka